"""Measured range expansion per macro event, for the calendar.

WHAT PROBLEM THIS SOLVES. `economic_calendar` labels every release `high`,
`medium` or `low`. Those three words were assigned by judgement and they answer
a TIMING question — "is this a scheduled discontinuity you need to be at the
screen for". The calendar card was reading them as a SIZING answer — "how much
wider than normal will this session be" — and the two diverge badly. Measured
over 3,677 sessions, CPI runs 1.06x a normal session and ranks 12th of 23;
triple witching runs 0.94x. Both are labelled `high`/`medium`. Nonfarm payrolls
is the only event in the study that survives BH-FDR, at 1.39x.

So this module does not touch `impact`. It adds a second, measured axis beside
it, and the UI is then free to answer each question with the field that
actually addresses it.

WHAT THE MULTIPLIER IS. Median absolute close-to-close move on the event date
divided by that session's own trailing 60-session median absolute move — "x a
day that was normal at the time". Magnitude only, no direction. Close-to-close
rather than RTH range because the 08:30 releases land before the bell.

THREE THINGS THAT MUST TRAVEL WITH THE NUMBER, or it gets over-read:
  1. `survives_fdr` — 23 events were tested, so one event at p=0.03 is what a
     null family looks like. Only NFP clears the correction.
  2. `rank_sd` — the yearly ranking is unstable (sd 4-8 places out of 21 for
     everything except NFP). A 1.25x is not a fixed property of the event.
  3. `next_session` — every value is near 1.0. Nothing carries past the print,
     so a wide event day says nothing about tomorrow.

Table is generated by `scripts/gen_event_impact.py` from
`research/market_movers/output/study.json`. Never edit the JSON by hand.
"""

from __future__ import annotations

import json
import logging
import os

logger = logging.getLogger(__name__)

_TABLE_PATH = os.path.join(os.path.dirname(__file__), "event_impact_tables.json")
_TABLE: dict | None = None

# An event with a multiplier at or above this AND a nominally significant
# rotation p-value passed one test but failed the family correction. It is
# reported as "unconfirmed" rather than promoted or discarded — the study's own
# phrasing for these is "possibly real, not established here".
_UNCONFIRMED_MULTIPLIER = 1.10
_UNCONFIRMED_P = 0.10


def table() -> dict:
    """The whole generated payload, including provenance and the metric text."""
    global _TABLE
    if _TABLE is None:
        try:
            with open(_TABLE_PATH, encoding="utf-8") as f:
                _TABLE = json.load(f)
        except Exception as e:
            # A missing table must degrade to "not measured", never to a
            # fabricated default. Every caller already handles None.
            logger.warning(f"event impact table unavailable: {e}")
            _TABLE = {"events": {}, "unmeasured": [], "error": str(e)}
    return _TABLE


def _band(row: dict) -> str:
    if row.get("survives_fdr"):
        return "established"
    if (row.get("multiplier") or 0) >= _UNCONFIRMED_MULTIPLIER and (row.get("p") or 1) < _UNCONFIRMED_P:
        return "unconfirmed"
    return "none"


def _headline(row: dict, band: str) -> str:
    """One descriptive sentence. States what was measured; never instructs."""
    mult = row["multiplier"]
    n = row["n"]
    of = table().get("n_events_ranked") or 23
    if band == "established":
        return (
            f"{mult:.2f}x a normal session's move, over {n} prints — the only one of "
            f"{of} tested events that survives the multiple-comparison correction."
        )
    if band == "unconfirmed":
        return (
            f"{mult:.2f}x a normal session's move over {n} prints (p={row['p']:.3f}), but "
            f"{of} events were tested and this does not survive the correction across them. "
            "Possibly real, not established."
        )
    if mult >= 0.98:
        return (
            f"{mult:.2f}x a normal session's move over {n} prints — indistinguishable from "
            f"an ordinary day. Ranked {row['rank']} of {of}."
        )
    return (
        f"{mult:.2f}x a normal session's move over {n} prints — NARROWER than an ordinary "
        f"day. Ranked {row['rank']} of {of}."
    )


def measured(name: str) -> dict | None:
    """The measured block for a calendar event name, or None if never measured.

    None is the honest answer for U-Mich preliminary, consumer confidence and
    the EIA petroleum report: they are on the calendar but were not in the
    study's universe. `unmeasured_reason` distinguishes "we looked and it is an
    ordinary day" from "nobody measured this".
    """
    t = table()
    row = (t.get("events") or {}).get(name)
    if not row:
        return None
    band = _band(row)
    out = {
        "multiplier": row["multiplier"],
        "ci95": row["ci95"],
        "n": row["n"],
        "p": row["p"],
        "survives_fdr": row["survives_fdr"],
        "rank": row["rank"],
        "of": t.get("n_events_ranked"),
        "next_session": row["next_session"],
        "share_over_1_5x": row["share_over_1_5x"],
        "rank_sd": row.get("rank_sd"),
        "share_in_top_k": row.get("share_in_top_k"),
        "exact": row.get("exact", True),
        "study_event": row.get("study_event"),
        "band": band,
        "headline": _headline(row, band),
    }
    if not out["exact"]:
        out["caveat"] = (
            f"Quoted from the pooled '{row['study_event']}' sample; this variant was "
            "never measured separately."
        )
    return out


def attach(events: list[dict]) -> list[dict]:
    """Add a `measured` block to each event, in place-safe fashion.

    Events with no measurement get `measured: None` EXPLICITLY rather than the
    key being absent — a missing key and a null read identically in JS, and the
    UI has to be able to say "not measured" out loud.
    """
    out = []
    for ev in events:
        out.append({**ev, "measured": measured(ev.get("name", ""))})
    return out


def provenance() -> dict:
    """Everything the UI needs to say where these numbers came from."""
    t = table()
    return {
        "metric": t.get("metric"),
        "sample": t.get("sample"),
        "generated": t.get("study_generated"),
        "n_events_ranked": t.get("n_events_ranked"),
        "quiet_day_median": t.get("quiet_day_median"),
    }
